/**
 * Default Dashboard Configurations
 *
 * These constants define the default home dashboard configurations
 * that are initialized when SUPER_ADMIN or TENANT_ADMIN users register.
 */

export type DefaultDashboardRole = 'SUPER_ADMIN' | 'TENANT_ADMIN';

export interface DefaultDashboardConfig {
  projectName: string;
  dashboardName: string;
  canvasConfig: string;
  nodes: string;
  dataSources: string;
  variables: string;
}

export const DEFAULT_DASHBOARD_CONFIGS: Record<DefaultDashboardRole, DefaultDashboardConfig> = {
  SUPER_ADMIN: {
    projectName: 'Super Admin Project',
    dashboardName: 'Super Admin Home',
    canvasConfig: JSON.stringify({
      mode: 'grid',
      width: 1500,
      height: 1000,
      background: { color: 'transparent' },
      theme: 'dawn',
      scaleMode: 'fit-min',
      previewAlignY: 'center',
      gridCols: 24,
      gridRowHeight: 50,
      gridGap: 5,
      gridEnabled: true,
      gridSize: 20,
    }),
    nodes: JSON.stringify([
      {
        id: 'de56f271-4e51-4e69-bc81-0058164d259e',
        type: 'chart/uplot-line',
        props: {
          title: 'Disk Usage',
          titleAlign: 'left',
          primaryColor: '#6965db',
          showLegend: true,
          timeRangePreset: 'all',
          data: [],
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { width: 0, color: '#c0c0c0', style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 0, y: 0 },
        size: { width: 600, height: 220 },
        data: [
          {
            targetProp: 'data',
            expression: '{{ ds.__platform__.data.disk_usage__history }}',
          },
        ],
        grid: { x: 0, y: 3, w: 12, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: '9a4bdf25-78cc-476b-9e8b-79d81583eecf',
        type: 'interaction/value-card-simple',
        props: {
          title: 'Total Devices',
          value: 0,
          unit: 'units',
          showUnit: true,
          precision: 0,
          showTrend: false,
          valueColor: 'auto',
          thresholds: '[]',
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 0, y: 0 },
        size: { width: 160, height: 80 },
        data: [
          {
            targetProp: 'value',
            expression: '{{ ds.__platform__.data.device_total }}',
          },
        ],
        grid: { x: 0, y: 0, w: 6, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'dc68f31a-2727-4c90-8219-69c0fab96739',
        type: 'interaction/value-card-simple',
        props: {
          title: 'Online Devices',
          value: 0,
          unit: 'units',
          showUnit: true,
          precision: 0,
          showTrend: false,
          valueColor: 'auto',
          thresholds: '[]',
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 20, y: 20 },
        size: { width: 160, height: 80 },
        data: [
          {
            targetProp: 'value',
            expression: '{{ ds.__platform__.data.device_activity }}',
          },
        ],
        grid: { x: 6, y: 0, w: 6, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'db3f0e48-720b-422f-8dd2-6628c766ecc9',
        type: 'interaction/value-card-simple',
        props: {
          title: 'Offline Devices',
          value: 0,
          unit: 'units',
          showUnit: true,
          precision: 0,
          showTrend: false,
          valueColor: 'auto',
          thresholds: '[]',
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 40, y: 40 },
        size: { width: 160, height: 80 },
        data: [
          {
            targetProp: 'value',
            expression: '{{ ds.__platform__.data.device_offline }}',
          },
        ],
        grid: { x: 12, y: 0, w: 6, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: '3e98c169-5679-4102-a2f4-967ca47cf4f5',
        type: 'interaction/value-card-simple',
        props: {
          title: 'Alarm Devices',
          value: 0,
          unit: 'units',
          showUnit: true,
          precision: 0,
          showTrend: false,
          valueColor: 'auto',
          thresholds: '[]',
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 60, y: 60 },
        size: { width: 160, height: 80 },
        data: [
          {
            targetProp: 'value',
            expression: '{{ ds.__platform__.data.alarm_device_total }}',
          },
        ],
        grid: { x: 18, y: 0, w: 6, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: '50440e62-8599-40c5-9f42-ca21b81d83aa',
        type: 'chart/uplot-line',
        props: {
          title: 'Memory Usage',
          titleAlign: 'left',
          primaryColor: '#6965db',
          showLegend: true,
          timeRangePreset: 'all',
          data: [],
        },
        baseStyle: {
          background: { color: '#ffffff', opacity: 1 },
          border: { width: 0, color: '#c0c0c0', style: 'solid', radius: 8 },
          opacity: 1,
        },
        position: { x: 20, y: 20 },
        size: { width: 600, height: 220 },
        data: [
          {
            targetProp: 'data',
            expression: '{{ ds.__platform__.data.memory_usage__history }}',
          },
        ],
        grid: { x: 12, y: 3, w: 12, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: '79521394-f416-4b1f-be7a-5844a7df4117',
        type: 'media/video-player',
        props: {
          src: 'https://pub-dd72232484fd4c78b094868481918d04.r2.dev/thingspanel-intro.mp4',
          mode: 'webrtc,mse,hls,mjpeg',
          background: false,
          visibilityThreshold: 0,
          objectFit: 'contain',
          borderWidth: 0,
          borderColor: '#000000',
          borderRadius: 0,
        },
        position: { x: 0, y: 0 },
        size: { width: 400, height: 300 },
        data: [],
        grid: { x: 0, y: 10, w: 12, h: 8, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'bfa90a38-5d22-4250-b21a-fd4f254a374e',
        type: 'media/iframe',
        props: {
          src: 'https://docs.thingspanel.cn/zh-Hans/',
          borderWidth: 0,
          borderColor: '#000000',
          borderRadius: 0,
        },
        position: { x: 0, y: 0 },
        size: { width: 400, height: 300 },
        data: [],
        grid: { x: 12, y: 10, w: 12, h: 8, static: false, isDraggable: true, isResizable: true },
      },
    ]),
    dataSources: '[]',
    variables: '[]',
  },

  TENANT_ADMIN: {
    projectName: 'Default Project',
    dashboardName: 'Tenant Admin Home',
    canvasConfig: JSON.stringify({
      mode: 'fixed',
      width: 1920,
      height: 1080,
      background: { color: '#f0f0f0', size: 'cover', repeat: 'no-repeat', attachment: 'scroll' },
      theme: 'dawn',
      scaleMode: 'fit-width',
      previewAlignY: 'center',
      gridCols: 24,
      gridRowHeight: 50,
      gridGap: 5,
      gridEnabled: true,
      gridSize: 20,
    }),
    nodes: JSON.stringify([
      // Device total card
      {
        id: 'c1',
        type: 'basic/rectangle',
        props: { fill: '#d64a92', stroke: '#d64a92', strokeWidth: 0, cornerRadius: 18 },
        position: { x: 72, y: 24 },
        size: { width: 430, height: 142 },
        data: [],
        grid: { x: 0, y: 0, w: 9, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c1t',
        type: 'basic/text',
        props: {
          text: 'Device Total',
          fontSize: 18,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '600',
          fill: '#ffffff',
        },
        position: { x: 96, y: 44 },
        size: { width: 100, height: 25 },
        data: [],
        grid: { x: 0, y: 0, w: 9, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c1v',
        type: 'basic/text',
        props: {
          text: '0 units',
          fontSize: 54,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#ffffff',
          lineHeight: 1,
        },
        position: { x: 96, y: 84 },
        size: { width: 200, height: 54 },
        data: [
          {
            targetProp: 'text',
            expression: '{{ ds.__platform__.data.device_total }}',
            transform: "return String(value ?? 0) + ' units';",
          },
        ],
        grid: { x: 0, y: 1, w: 9, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      // Online devices card
      {
        id: 'c3',
        type: 'basic/rectangle',
        props: { fill: '#7059d9', stroke: '#7059d9', strokeWidth: 0, cornerRadius: 18 },
        position: { x: 980, y: 24 },
        size: { width: 430, height: 142 },
        data: [],
        grid: { x: 9, y: 0, w: 9, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c3t',
        type: 'basic/text',
        props: {
          text: 'Online Devices',
          fontSize: 18,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '600',
          fill: '#ffffff',
        },
        position: { x: 1004, y: 44 },
        size: { width: 120, height: 25 },
        data: [],
        grid: { x: 9, y: 0, w: 9, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c3v',
        type: 'basic/text',
        props: {
          text: '0 units',
          fontSize: 54,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#ffffff',
          lineHeight: 1,
        },
        position: { x: 1004, y: 84 },
        size: { width: 200, height: 54 },
        data: [
          {
            targetProp: 'text',
            expression: '{{ ds.__platform__.data.device_online }}',
            transform: "return String(value ?? 0) + ' units';",
          },
        ],
        grid: { x: 9, y: 1, w: 9, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      // Offline devices card
      {
        id: 'c2',
        type: 'basic/rectangle',
        props: { fill: '#62b8f9', stroke: '#62b8f9', strokeWidth: 0, cornerRadius: 18 },
        position: { x: 526, y: 24 },
        size: { width: 430, height: 142 },
        data: [],
        grid: { x: 0, y: 0, w: 9, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c2t',
        type: 'basic/text',
        props: {
          text: 'Offline Devices',
          fontSize: 18,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '600',
          fill: '#ffffff',
        },
        position: { x: 550, y: 44 },
        size: { width: 120, height: 25 },
        data: [],
        grid: { x: 0, y: 0, w: 9, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c2v',
        type: 'basic/text',
        props: {
          text: '0 units',
          fontSize: 54,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#ffffff',
          lineHeight: 1,
        },
        position: { x: 550, y: 84 },
        size: { width: 200, height: 54 },
        data: [
          {
            targetProp: 'text',
            expression: '{{ ds.__platform__.data.device_offline }}',
            transform: "return String(value ?? 0) + ' units';",
          },
        ],
        grid: { x: 0, y: 1, w: 9, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      // Alarm stat card
      {
        id: 'c4',
        type: 'basic/rectangle',
        props: { fill: '#ff5a34', stroke: '#ff5a34', strokeWidth: 0, cornerRadius: 18 },
        position: { x: 1434, y: 24 },
        size: { width: 430, height: 142 },
        data: [],
        grid: { x: 18, y: 0, w: 6, h: 3, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c4t',
        type: 'basic/text',
        props: {
          text: 'Alarm Count',
          fontSize: 18,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '600',
          fill: '#ffffff',
        },
        position: { x: 1458, y: 44 },
        size: { width: 100, height: 25 },
        data: [],
        grid: { x: 18, y: 0, w: 6, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'c4v',
        type: 'basic/text',
        props: {
          text: '0 units',
          fontSize: 54,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#ffffff',
          lineHeight: 1,
        },
        position: { x: 1458, y: 84 },
        size: { width: 200, height: 54 },
        data: [
          {
            targetProp: 'text',
            expression: '{{ ds.__platform__.data.alarm_device_total }}',
            transform: "return String(value ?? 0) + ' units';",
          },
        ],
        grid: { x: 18, y: 1, w: 6, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      // Online trend chart
      {
        id: 'p3',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 620, y: 194 },
        size: { width: 860, height: 384 },
        data: [],
        grid: { x: 0, y: 3, w: 12, h: 8, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p3t',
        type: 'basic/text',
        props: {
          text: 'Device Online Trend (12h)',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#2563eb',
        },
        position: { x: 640, y: 214 },
        size: { width: 200, height: 22 },
        data: [],
        grid: { x: 0, y: 3, w: 12, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p3c',
        type: 'chart/echarts-line',
        props: {
          title: '',
          titleAlign: 'left',
          primaryColor: '#5b8cff',
          showLegend: false,
          showXAxis: true,
          showYAxis: true,
          smooth: true,
          showArea: true,
          timeRangePreset: 'all',
          data: [],
        },
        position: { x: 640, y: 256 },
        size: { width: 816, height: 286 },
        data: [
          {
            targetProp: 'data',
            expression: '{{ ds.__platform__.data.device_online__history }}',
          },
        ],
        grid: { x: 0, y: 4, w: 12, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      // Operating guide
      {
        id: 'p1',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 72, y: 194 },
        size: { width: 520, height: 384 },
        data: [],
        grid: { x: 0, y: 3, w: 4, h: 8, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1t',
        type: 'basic/text',
        props: {
          text: 'Quick Start Guide',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 96, y: 214 },
        size: { width: 130, height: 22 },
        data: [],
        grid: { x: 0, y: 3, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r1',
        type: 'basic/rectangle',
        props: { fill: '#f7fbff', stroke: '#dbe7ff', strokeWidth: 1, cornerRadius: 18 },
        position: { x: 96, y: 258 },
        size: { width: 472, height: 74 },
        data: [],
        grid: { x: 0, y: 4, w: 4, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r1t',
        type: 'basic/text',
        props: {
          text: 'Add Device',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 164, y: 274 },
        size: { width: 100, height: 22 },
        data: [],
        grid: { x: 0, y: 4, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r1d',
        type: 'basic/text',
        props: {
          text: 'Connect devices to platform for unified management',
          fontSize: 13,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '500',
          fill: '#6b7280',
          lineHeight: 1.5,
        },
        position: { x: 164, y: 300 },
        size: { width: 250, height: 19 },
        data: [],
        grid: { x: 0, y: 5, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r2',
        type: 'basic/rectangle',
        props: { fill: '#f8fafc', stroke: '#e5ebf4', strokeWidth: 1, cornerRadius: 18 },
        position: { x: 96, y: 352 },
        size: { width: 472, height: 74 },
        data: [],
        grid: { x: 0, y: 5, w: 4, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r2t',
        type: 'basic/text',
        props: {
          text: 'Configure Device',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 164, y: 368 },
        size: { width: 120, height: 22 },
        data: [],
        grid: { x: 0, y: 5, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r2d',
        type: 'basic/text',
        props: {
          text: 'Set properties, parameters and data collection rules',
          fontSize: 13,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '500',
          fill: '#6b7280',
          lineHeight: 1.5,
        },
        position: { x: 164, y: 394 },
        size: { width: 250, height: 19 },
        data: [],
        grid: { x: 0, y: 6, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r3',
        type: 'basic/rectangle',
        props: { fill: '#fff8f1', stroke: '#ffe3c7', strokeWidth: 1, cornerRadius: 18 },
        position: { x: 96, y: 446 },
        size: { width: 472, height: 74 },
        data: [],
        grid: { x: 0, y: 6, w: 4, h: 2, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r3t',
        type: 'basic/text',
        props: {
          text: 'Create Dashboard',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 164, y: 462 },
        size: { width: 130, height: 22 },
        data: [],
        grid: { x: 0, y: 6, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p1r3d',
        type: 'basic/text',
        props: {
          text: 'Combine components to build real-time monitoring views',
          fontSize: 13,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '500',
          fill: '#6b7280',
          lineHeight: 1.5,
        },
        position: { x: 164, y: 488 },
        size: { width: 250, height: 19 },
        data: [],
        grid: { x: 0, y: 7, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      // Overview panel
      {
        id: 'p4',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 1504, y: 194 },
        size: { width: 360, height: 384 },
        data: [],
        grid: { x: 12, y: 3, w: 4, h: 8, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p4t',
        type: 'basic/text',
        props: {
          text: 'Overview',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 1528, y: 214 },
        size: { width: 80, height: 22 },
        data: [],
        grid: { x: 12, y: 3, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p4g',
        type: 'chart/echarts-gauge',
        props: {
          title: ' ',
          primaryColor: '#5b8cff',
          max: 100,
          data: { value: 0, name: 'Online Rate' },
        },
        position: { x: 1528, y: 252 },
        size: { width: 312, height: 176 },
        data: [
          {
            targetProp: 'data',
            expression: '{{ ds.__platform__.data }}',
            transform:
              "const total = Number(value?.device_total ?? 0); const online = Number(value?.device_online ?? 0); return { value: total > 0 ? Math.round((online / total) * 100) : 0, name: 'Online Rate' };",
          },
        ],
        grid: { x: 12, y: 4, w: 4, h: 4, static: false, isDraggable: true, isResizable: true },
      },
      // Alarm info panel
      {
        id: 'p5',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 72, y: 602 },
        size: { width: 520, height: 339 },
        data: [],
        grid: { x: 0, y: 11, w: 6, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p5t',
        type: 'basic/text',
        props: {
          text: 'Alarm Information',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 96, y: 622 },
        size: { width: 120, height: 22 },
        data: [],
        grid: { x: 0, y: 11, w: 6, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p5c',
        type: 'custom/alert-list',
        props: {
          maxItems: 6,
          showTime: true,
          showSource: true,
          showDetail: true,
          titleFontSize: 15,
          detailFontSize: 12,
          timeFontSize: 11,
          itemRadius: 14,
          items: [],
          autoScroll: true,
          scrollSpeed: 'normal',
        },
        baseStyle: {
          background: { color: 'transparent', opacity: 1 },
          opacity: 1,
        },
        position: { x: 104, y: 664 },
        size: { width: 448, height: 251 },
        data: [
          {
            targetProp: 'items',
            expression: '{{ ds.__platform__.data.home_alarm_items }}',
          },
        ],
        grid: { x: 0, y: 12, w: 6, h: 6, static: false, isDraggable: true, isResizable: true },
      },
      // Recent data panel
      {
        id: 'p6',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 620, y: 602 },
        size: { width: 856, height: 339 },
        data: [],
        grid: { x: 6, y: 11, w: 6, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p6t',
        type: 'basic/text',
        props: {
          text: 'Recent Data Reports',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 640, y: 622 },
        size: { width: 130, height: 22 },
        data: [],
        grid: { x: 6, y: 11, w: 6, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p6c',
        type: 'basic/table',
        props: {
          columns: [
            { key: 'device', title: 'Device Name', align: 'left' },
            { key: 'metric', title: 'Metric', align: 'left' },
            { key: 'value', title: 'Value', align: 'right' },
            { key: 'time', title: 'Last Update', align: 'right' },
          ],
          data: [],
          showHeader: true,
          headerFontSize: 13,
          bodyFontSize: 12,
          cellPadding: 10,
        },
        position: { x: 640, y: 664 },
        size: { width: 812, height: 228 },
        data: [
          {
            targetProp: 'data',
            expression: '{{ ds.__platform__.data.home_latest_report_rows }}',
          },
        ],
        grid: { x: 6, y: 12, w: 6, h: 6, static: false, isDraggable: true, isResizable: true },
      },
      // Product intro panel
      {
        id: 'p7',
        type: 'basic/rectangle',
        props: { fill: '#ffffff', stroke: '#e8edf5', strokeWidth: 1, cornerRadius: 20 },
        position: { x: 1500, y: 602 },
        size: { width: 364, height: 347 },
        data: [],
        grid: { x: 12, y: 11, w: 4, h: 7, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: 'p7t',
        type: 'basic/text',
        props: {
          text: 'Product Introduction',
          fontSize: 16,
          fontFamily: 'Inter, Noto Sans SC, sans-serif',
          fontWeight: '700',
          fill: '#1f2937',
        },
        position: { x: 1524, y: 622 },
        size: { width: 150, height: 22 },
        data: [],
        grid: { x: 12, y: 11, w: 4, h: 1, static: false, isDraggable: true, isResizable: true },
      },
      {
        id: '60118ec9-b1ec-43e6-a62a-1b94a38e144e',
        type: 'media/video-player',
        props: {
          src: 'https://pub-dd72232484fd4c78b094868481918d04.r2.dev/thingspanel-intro.mp4',
          mode: 'webrtc,mse,hls,mjpeg',
          background: false,
          visibilityThreshold: 0,
          objectFit: 'cover',
          borderWidth: 0,
          borderColor: '#000000',
          borderRadius: 0,
        },
        position: { x: 1530, y: 664 },
        size: { width: 310, height: 240 },
        data: [],
        grid: { x: 12, y: 12, w: 4, h: 6, static: false, isDraggable: true, isResizable: true },
      },
    ]),
    dataSources: '[]',
    variables: '[]',
  },
};
